### ISSUE TITLE
cachix-ignore

### ISSUE THREAD

**Issue by dysinger** [cachix/cachix-action#75] opened 2021-01-15 21:45 UTC
It would be nice to avoid pushing some things to the cache. We build all of our targets in one pass with Nix on GitHub but we don't want our docker images pushed to cachix and bloating our cache.

**Comment by domenkozar** [comment] 2021-01-15 22:33
What do you want to filter on - derivation name?

**Comment by hmenke** [comment] 2021-02-05 12:00
I have the same request, but for me it's flake inputs.  Most of my cache space is taken up by different `nixexprs.tar.xz`.

**Comment by domenkozar** [comment] 2021-02-05 12:05
@hmenke what's the full store path?

**Comment by hmenke** [comment] 2021-02-05 12:12
@domenkozar For example this one: https://hmenke.cachix.org/64rwqa366f99rd020b2isz634b7mf43b.narinfo

**Comment by domenkozar** [comment] 2021-02-08 12:00
That one is trickier to filter out because the name of the derivation is always `-source`.

For flakes it would be better to have a settings what to cache - everything | dev | runtime.

**Comment by InternetUnexplorer** [comment] 2021-02-16 22:46
I've been using a GH Action to build my [kwin-lowlatency overlay](https://github.com/InternetUnexplorer/kwin-lowlatency-overlay) every time one of the unstable channels updates, and I noticed that most of the storage is being used up by `nixexprs.tar.xz`s:

![2021-02-16_14-35](https://user-images.githubusercontent.com/19176616/108130261-3ac59580-7064-11eb-83a5-5132fe6739cc.png)

I'm not sure if this is caused by me specifying `nix_path: nixpkgs=channel:nixos-unstable(-small)` in my [`build.yml`](https://github.com/InternetUnexplorer/kwin-lowlatency-overlay/blob/6aa11d1cc5fac3d9d12c4f6bd04e8ca5cade5364/.github/workflows/build.yml), or if this is just something that happens all the time when using `install-nix-action`.

Regardless, it would be great if there were a way to filter these out, either by a user-configurable filter or just as a special case. 

Resolving the `channel:` URI seems to be a [special case](https://github.com/NixOS/nix/blob/4e98f0345c144b9d85bed1f6b0bc509bf7ddc000/src/libstore/filetransfer.cc#L39) in Nix itself, if that's at all helpful.

**Comment by domenkozar** [comment] 2021-02-17 10:20
Thanks all for the feedback, I've bumped the priority on this one.

**Comment by domenkozar** [comment] 2021-02-17 12:29
https://github.com/cachix/cachix-action/pull/77

**Comment by domenkozar** [comment] 2021-04-02 15:46
This was released as part of https://github.com/cachix/cachix-action/releases/tag/v9, would you consider it fixed?

**Comment by InternetUnexplorer** [comment] 2021-04-02 21:16
I've been [using it since it was merged](https://github.com/InternetUnexplorer/kwin-lowlatency-overlay/commit/71689c6fe9741890726665ba65a58939017a6c74#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721), it works great! Thank you! :)

**Comment by domenkozar** [comment] 2021-09-15 07:51
Closing as fixed due to no complains

**Closed by domenkozar** 2021-09-15 07:51 UTC
Labels: enhancement
